name: grock
description: Snackbars, No Context Extension, Custom Widgets, Widget Extensions, Fast Tools, IOS Style Widget and Tools.
version: 0.0.6+2
# author: Ahmet Özberk <ahmet.ozberk.mrs@gmail.com>
homepage: https://github.com/ahmet-ozberk/grock

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
