name: grock
description: Snackbar, Toast, No Context Extension, Custom Widgets, Widget Extensions, Fast Tools, IOS Style Widget and Tools.
version: 0.0.8+9
# author: Ahmet Özberk <ahmet.ozberk.mrs@gmail.com>
homepage: https://github.com/ahmet-ozberk/grock

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
