name: grock
description: A flutter extension project.
version: 0.0.2+3
# author: Ahmet Özberk <ahmet.ozberk.mrs@gmail.com>
homepage: https://github.com/ahmet-ozberk/grock

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.0.5
  package_info_plus: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter: